import { A3Pro, MiBand6, MiBand7, MiBuds1, MiBuds2, MiBuds31, MiBuds32, MiCarCharger1, MiCarCharger2, MiCarCharger3, MiCompact1, MiCompact2, MiCompact3, MiEarphones1, MiEarphones2, MiEarphones3, MiRepeater1, MiRepeater2, MiTv1, MiTv2, PocoM6Pro1, PocoM6Pro3, PowerBank1, PowerBank2, Redmi131, Redmi132, Redmi13C, Redmi14C1, Redmi14C2, RedmiA3x1, RedmiA3x2, RedmiA3x3, RedmiNote131, RedmiNote133, RedmiNote13Pro1, RedmiNote13Pro2, RedmiNote13Pro3, RedmiNote13ProPlus1, RedmiNote13ProPlus2, RedmiNote13ProPlus3, Storage, Tablet1, Tablet2, Tablet3, WatchW1, WirelessBuds1, WirelessBuds2, XiaomiTv1, XiaomiTv2, XiaomiTv3, XiaomiTv4, XiaomiTv5, XiaomiWatch1, XiaomiWatch2, XiaomiWatch3 } from "../constants";

export const ACCESS_TOKEN = "access";
export const REFRESH_TOKEN = "refresh"

export const baseUrl = "http://localhost:8000"


export const Filters = ["Redmi", "Poco", "Mi Phones", "watches", "Audio", "Screens", "Tablets", "Accessories"];

export const FeaturesList = [
    {
        icon: Storage,
        iconbg: 'bg-icon-color1',
        features: 'RAM 6GB | 8GB',
        xalign: 'left-[67%]',
        top: 'top-0',
        smalign: 'max-md:left-[57%]',

    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color2',
        features: '128GB, 256GB',
        xalign: 'left-[72%]',
        top: 'top-28',
        smalign: 'max-md:left-[57%]',
        smtop: 'max-sm:top-[90px]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color3',
        features: 'Battery 500mah',
        xalign: 'left-[67%]',
        top: 'top-56',
        smalign: 'max-md:left-[57%]',
        smtop: 'max-sm:top-[180px]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color4',
        features: 'MainCamera 64MP',
        xalign: 'left-[72%]',
        top: 'top-[336px]',
        smalign: 'max-md:left-[57%]',
        smtop: 'max-sm:top-[270px]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color1',
        features: 'Front Camera 16MP',
        xalign: 'left-[67%]',
        top: 'top-[448px]',
        smalign: 'max-md:left-[57%]',
        smtop: 'max-sm:top-[360px]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color2',
        features: '6.67 Inches Display',
        xalign: 'left-[18%]',
        top: 'top-0',
        smalign: 'max-md:left-[3%]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color3',
        features: 'MediaTek Processor',
        xalign: 'left-[10%]',
        top: 'top-28',
        smalign: 'max-md:left-[3%]',
        smtop: 'max-sm:top-[90px]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color4',
        features: '5G Connectivity',
        xalign: 'left-[18%]',
        top: 'top-56',
        smalign: 'max-md:left-[3%]',
        smtop: 'max-sm:top-[180px]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color1',
        features: 'Blur, Silver, Black',
        xalign: 'left-[10%]',
        top: 'top-[336px]',
        smalign: 'max-md:left-[3%]',
        smtop: 'max-sm:top-[270px]'
    },
    {
        icon: Storage,
        iconbg: 'bg-icon-color2',
        features: 'Android 12 OS',
        xalign: 'left-[18%]',
        top: 'top-[448px]',
        smalign: 'max-md:left-[3%]',
        smtop: 'max-sm:top-[360px]'
    },
]

export const heroProducts = [
    {
        id: 1,
        name: "Redmi Note 13 8/256",
        original_price: 33000.00,
        current_price: 22300.00,
        category: "smartphone",
        image: RedmiNote131,
        stock: "In Stock",
        features: {"RAM": "6GB, 8GB", "colors": "Midnight Black, Mint Green, Ice Blue, Ocean Sunset", "battery": "5000mAh, 33W", "display": "6.67 inches, AMOLED, 120Hz", "processor": "Qualcomm SM6225 Snapdragon 685", "main_camera": "108MP + 8MP + 2MP", "connectivity": "Dual SIM, 3G, 4G, Wi-Fi", "front_camera": "16MP", "internal_storage": "128GB, 256GB", "operating_system": "Android 13, MIUI 14"},
        additional_info: "The Redmi Note 13 stands out with its high-resolution 108MP main camera, which is rare in this price category. It offers a versatile photography experience with additional 8MP ultra-wide and 2MP macro lenses, making it ideal for users who love capturing detailed photos. The phone excels in different lighting conditions, allowing for great shots, whether close-ups, wide-angle landscapes, or everyday scenes.The phone’s 6.67-inch AMOLED display with a 120Hz refresh rate provides a smooth and fluid user experience, whether for gaming, browsing, or media consumption. The AMOLED panel ensures vivid colors and deep contrasts, enhancing video playback quality and gaming visuals. The 120Hz refresh rate reduces motion blur, making interactions smoother and more responsive.Powered by the Qualcomm Snapdragon 685, this device guarantees fast and efficient performance. Whether running multiple apps or playing graphics-intensive games, the Snapdragon processor ensures a seamless experience without noticeable lag, making",
        thumbnail_1: RedmiNote131,
        thumbnail_2: RedmiNote133,
        slogan: "Master Light, Capture Night",
        feature_1: "108MP Camera",
        feature_2: "5000mAh Battery",
    },
    {
        id: 2,
        name: "Redmi A3 Pro",
        original_price: 0.00,
        current_price: 12000.00,
        category: "smartphone",
        image: A3Pro,
        stock: "In Stock",
        features: {"OS": "Android 14, HyperOS", "Ram": "4GB RAM", "Colors": "Blue; other colors", "Battery": "5160mAh, 10W wired", "Display": "6.88-inch IPS LCD, 90Hz, 720 x 1640 pixels", "Internal": "128GB", "Processor": "Mediatek Helio G81 Ultra, Octa-core ", "Main_camera": "50 MP (wide)", "Connectivity": "LTE, Bluetooth 5.4, USB Type-C", "Front_camera": "Yes (selfie camera)"},
        additional_info: "The Redmi A3 Pro features a large 6.88-inch IPS LCD display with a smooth 90Hz refresh rate, providing an enhanced visual experience for scrolling and watching videos. With a resolution of 720 x 1640 pixels, the screen delivers vibrant colors and decent clarity, ensuring an enjoyable viewing experience.This smartphone is powered by the Mediatek Helio G81 Ultra chipset, which features an octa-core processor (comprising 2x2.0 GHz Cortex-A75 and 6x1.8 GHz Cortex-A55), paired with a capable 4GB RAM and 128GB of internal storage, utilizing eMMC 5.1 technology for efficient data handling. The dedicated microSDXC card slot allows for easy expansion, ensuring that users have ample storage for apps, photos, and videos.For photography, the Redmi A3 Pro boasts a 50 MP main camera, equipped with features like LED flash and HDR for capturing stunning photos. It supports 1080p video recording at 30fps, enabling users to document their moments in high definition. The selfie camera also supports 1080p video, ensuring clear and detailed video calls.The device is powered by a robust 5160mAh battery, providing ample life for day-to-day use, though it supports 10W wired charging, which means charging speeds may be relatively slow.In terms of connectivity, the Redmi A3 Pro covers all bases with support for GSM, HSPA, and LTE networks. It features Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.4, and NFC capabilities (depending on the market), making it versatile for various connectivity needs. Additionally, it includes a USB Type-C 2.0 port for charging and data transfer.Running on Android 14 with HyperOS, the phone provides a modern software experience with planned updates for future enhancements. With side-mounted fingerprint recognition, an accelerometer, and a compass, the phone offers practical features for security and navigation.",
        thumbnail_1: A3Pro,
        slogan: "Power On, Last Longer",
        feature_1: "5160 mAh, 10W Battery",
        feature_2: "4GB RAM 128GB Internal",
    },
]

export const latestProduct = [
    {
        id: 12,
        name: "Redmi 14C 8/256",
        original_price: 0.00,
        current_price: 16999.00,
        category: "smartphone",
        image: Redmi14C1,
        stock: "In Stock",
        features: {"OS": "Android 14, HyperOS", "Weight": "204 / 207 / 211 g", "Battery": "5160mAh, 18W ", "Display": "6.88-inch IPS LCD, 120Hz, 720 x 1640 pixels", "Network": "GSM / HSPA / LTE", "Processor": "Mediatek Helio G81 Ultra, Octa-core", "Dimensions": "171.9 x 77.8 x 8.2 mm", "Main_Camera": "Dual: 50 MP (wide), 2 MP (depth)", "Selfie_Camera": "13 MP"},
        additional_info: "The Redmi 14C, announced on August 30, 2024, combines a modern design with robust features, making it a competitive choice in the mid-range smartphone market. Its dimensions of 171.9 x 77.8 x 8.2 mm and a weight of approximately 204 to 211 grams contribute to a solid build quality, featuring a glass front, a plastic frame, and options for a glass back or eco-friendly silicone polymer back.This device supports dual SIM functionality (Nano-SIM, dual stand-by), providing users with the convenience of managing two phone numbers seamlessly.The 6.88-inch IPS LCD display boasts a resolution of 720 x 1640 pixels with a 120Hz refresh rate, enhancing the visual experience with smooth scrolling and vibrant colors. The display also offers a typical brightness of 450 nits, ensuring good visibility even in bright conditions.Powered by the Mediatek Helio G81 Ultra chipset, the Redmi 14C features an octa-core CPU that includes 2x2.0 GHz Cortex-A75 and 6x1.8 GHz Cortex-A55 cores, paired with the Mali-G52 MC2 GPU for efficient graphics performance. The phone comes with various internal storage options ranging from 128GB to 256GB, along with multiple RAM configurations (4GB, 6GB, or 8GB), supporting expandable storage through a microSDXC card slot.The camera system includes a dual main camera setup featuring a 50 MP wide lens and a 2 MP depth lens, complemented by an auxiliary lens. The camera supports features like HDR and can record videos at 1080p. For selfies, the front-facing camera offers a 13 MP sensor, also capable of 1080p video recording.The Redmi 14C is equipped with a 5160 mAh battery, supporting 18W wired charging, which allows for extended usage on a single charge. Connectivity options include Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.4, and a USB Type-C 2.0 port, alongside various positioning systems..",
        thumbnail_1: Redmi14C1,
        thumbnail_2: Redmi14C2,
        feature_1: "4GB, 6GB, 8GB RAM",
        feature_2: "128GB, 256GB Internal",
        feature_3: "Battery 5160mAh",
        feature_4: "Battery 18W",
        feature_5: "Main Camera 50MP",
        feature_6: "Front Camera 13MP",
        feature_7: "MediaTek Processor",
        feature_8: "6.88 Inches Display",
        feature_9: "Android 14",
        feature_10: "204 - 211 grams",
    },
]

export const offerProducts = [
    {
        id: 13,
        name: "Xiaomi Smart Band 9",
        original_price: 8500.00,
        current_price: 7500.00,
        discount: "12%",
        category: "watch",
        image: XiaomiWatch1,
        stock: "In Stock",
        enddate: "2024-12-31T23:59:59Z",
        features: {
            "Size": "46.53 x 21.63 x 10.95 mm",
            "Display": "AMOLED, 1.62 inches",
            "Weight": "15.8g",
            "SportsModes": "150+",
            "Colorways": "Midnight Black, Glacier Silver, Mystic Rose, Arctic Blue",
            "Connectivity": "Bluetooth 5.4",
            "Battery": "233mAh"
        },
        additional_info: "The Xiaomi Smart Band 9 is a sleek and feature-packed fitness tracker designed for users seeking style, functionality, and performance. It boasts a compact design, with dimensions of 46.53 x 21.63 x 10.95 mm and a lightweight build of just 15.8g, making it comfortable to wear all day. The device features a stunning AMOLED display measuring 1.62 inches, delivering vibrant colors and crisp details. With over 150 sports modes, the Smart Band 9 caters to fitness enthusiasts, offering comprehensive tracking for various activities. It supports Bluetooth 5.4 for seamless connectivity with smartphones and other devices, while its 233mAh battery provides long-lasting power. Available in stylish colorways such as Midnight Black, Glacier Silver, Mystic Rose, and Arctic Blue, the band blends fashion with functionality, making it an ideal choice for fitness-conscious users.",
        thumbnail_1: XiaomiWatch1,
        thumbnail_2: XiaomiWatch2,
        thumbnail_3: XiaomiWatch3,
    },
    {
        id: 14,
        name: "Mi Buds 3 Lite",
        original_price: 9000.00,
        current_price: 6500.00,
        discount: "28%",
        category: "audio",
        image: MiBuds1,
        stock: "In Stock",
        enddate: "2024-11-31T23:59:59Z",
        features: {
            "WirelessConnection": "Bluetooth 5.2",
            "CommunicationRange": "10m (open space free of obstacles)",
            "DustWaterResistance": "IP54",
            "EarbudBatteryLife": "Approx. 5 hours",
            "ChargingCaseBatteryLife": "Approx. 18 hours",
            "EarbudDimensions": "24.5 x 16.7 x 24.6 mm",
            "ChargingCaseDimensions": "60 x 46 x 23.7 mm",
            "ChargingPort": "Type-C",
            "SingleEarbudWeight": "Approx. 4.2g",
            "TotalWeightWithChargingCase": "Approx. 36g"
          },
        additional_info: "The Mi Buds 3 Lite offer a reliable and high-quality audio experience with a Bluetooth 5.2 wireless connection, ensuring stable performance and low latency. With a communication range of up to 10 meters in open spaces, these earbuds provide freedom of movement without losing connectivity. They feature an IP54 rating, making them resistant to dust and splashes, perfect for workouts or daily use in different environments.The earbuds themselves have a battery life of approximately 5 hours, while the charging case extends this to a total of 18 hours of listening time, ensuring you can enjoy your music all day long. The earbuds are compact, with dimensions of 24.5 x 16.7 x 24.6 mm, and weigh just 4.2g each, making them lightweight and comfortable to wear. The charging case is also small and portable, measuring 60 x 46 x 23.7 mm, and comes with a Type-C charging port for fast charging. Overall, with a total weight of 36g (including the case), the Mi Buds 3 Lite provide a perfect blend of portability, durability, and performance.",
        thumbnail_1: MiBuds1,
        thumbnail_2: MiBuds2,
    },
    {
        id: 9,
        name: "Redmi Note 13 Pro+",
        original_price: 78000.00,
        current_price: 55999.00,
        discount: "21",
        category: "smartphone",
        image: RedmiNote13ProPlus1,
        stock: "Limited",
        enddate: "2024-12-31T23:59:59Z",
        features: {"ram": "12GB", "colors": "Midnight Black, Moonlight White, Aurora Purple, Camo Green", "battery": "5000 mAh, 120W ", "display": "AMOLED, 6.67 inches, 1220 x 2712 pixels", "internal": "512GB", "processor": "Mediatek Dimensity 7200 Ultra, Octa-core", "main_camera": "200 MP (wide), 8 MP (ultrawide), 2 MP (macro)", "connectivity": "5G", "front_camera": "16 MP"},
        additional_info: "The Redmi Note 13 Pro+ is a feature-rich smartphone that balances performance and aesthetics. It is powered by the Mediatek Dimensity 7200 Ultra chipset, delivering impressive processing capabilities with its octa-core CPU. This makes it suitable for various tasks, including gaming and multitasking.With memory configurations of 8GB, 12GB, or 16GB of RAM paired with 256GB or 512GB of internal storage, users can select the variant that best meets their needs for app installations and data storage.The device features a stunning 6.67-inch AMOLED display with a resolution of 1220 x 2712 pixels, offering vibrant colors and sharp details. The display supports Dolby Vision and HDR10+, enhancing the viewing experience for media consumption.Photography is a highlight of the Redmi Note 13 Pro+, equipped with a 200 MP main camera, complemented by an 8 MP ultrawide and a 2 MP macro lens, allowing for versatile shooting options. The 16 MP front camera is perfect for selfies and video calls.Powering the device is a 5000 mAh battery, ensuring long-lasting usage. The phone supports 120W wired charging, which can recharge the device to full capacity in just 19 minutes, catering to users with a busy lifestyle.",
        thumbnail_1: RedmiNote13ProPlus1,
        thumbnail_2: RedmiNote13ProPlus2,
        thumbnail_3: RedmiNote13ProPlus3,
    },
    {
        id: 15,
        name: "Mi TV Box S",
        original_price: 25000.00,
        current_price: 18500.00,
        discount: "15",
        category: "accessory",
        image: MiTv1,
        stock: "In Stock",
        enddate: "2024-12-31T23:59:59Z",
        features: {
            "OutputResolution": "4K (3840 x 2160)",
            "CPU": "Cortex-A53 Quad-core 64bit",
            "GPU": "Mali-450",
            "RAM": "2GB DDR3",
            "Storage": "8GB eMMC",
            "OperatingSystem": "Android 8.1",
            "WiFi": "802.11a/b/g/n/ac 2.4GHz/5GHz",
            "Bluetooth": "4.1",
            "Sockets": "HDMI2.0a, USB2.0, PowerInterface1, AudioOut",
        },
        additional_info: "The Mi TV Box S is a powerful and compact streaming device that supports 4K output resolution at 3840 x 2160, delivering stunning visual clarity for your media. Powered by a Cortex-A53 Quad-core 64bit CPU and a Mali-450 GPU, it ensures smooth performance for apps, streaming, and video playback. With 2GB of DDR3 RAM and 8GB of eMMC storage, users can enjoy a seamless experience while installing and running apps.Running on Android 8.1, the Mi TV Box S provides access to a wide range of Android apps, including popular streaming platforms, with smooth multitasking. It supports Wi-Fi (802.11a/b/g/n/ac) on both 2.4GHz and 5GHz bands for fast and stable connectivity. The device also includes Bluetooth 4.1 for connecting wireless accessories such as controllers and headphones.In terms of connectivity, the Mi TV Box S features essential sockets including one HDMI2.0a port for high-definition output, one USB2.0 port for connecting external devices, one power interface, and an audio out port for enhanced sound integration. The compact design and powerful capabilities make it an excellent choice for transforming any TV into a smart entertainment hub.",
        thumbnail_1: MiTv1,
        thumbnail_2: MiTv2,
    },
]

export const products = [
    {
        id: 32,
        name: "Xiaomi Pad S",
        original_price: 29000.00,
        current_price: 23000.00,
        discount: "12",
        category: "tablet",
        image: Tablet3,
        stock: "In Stock",
        feature_1: "22 W Charger",
        feature_2: "4GB RAM",
        feature_3: "128GB Storage",
        features: {
            "display_size": "11 inches",
            "resolution": "2560 x 1600 pixels",
            "hdr_support": true,
            "processor": "Qualcomm Snapdragon 860",
            "ram": "6GB",
            "storage_options": "128GB, 256GB",
            "rear_camera": "13MP",
            "front_camera": "8MP",
            "connectivity": "Wi-Fi 5, Bluetooth 5.0",
            "battery_capacity": "8720mAh",
            "charging_speed": "22.5W Fast Charging",
          },
        additional_info: "The Xiaomi Pad 5 is a powerful and versatile tablet with an 11-inch WQHD+ display, offering a resolution of 2560 x 1600 pixels. The screen supports a 120Hz refresh rate and HDR10, making it perfect for watching videos, gaming, and productivity tasks with vibrant visuals and smooth transitions. Powered by the Qualcomm Snapdragon 860 processor, along with 6GB of RAM and 128GB or 256GB of storage options, the Pad 5 delivers fast and efficient performance for multitasking, gaming, and media consumption.The tablet comes with a 13MP rear camera and an 8MP front camera, ideal for video calls, capturing photos, and scanning documents. It supports quad speakers with Dolby Atmos, providing an immersive audio experience for media playback. Connectivity options include Wi-Fi 5 and Bluetooth 5.0, ensuring fast wireless connections. The Xiaomi Pad 5 has a large 8720mAh battery, supporting 22.5W fast charging, offering excellent battery life for extended usage. With a sleek, premium design and running MIUI for Pad based on Android, it is priced at around $400, offering a great balance of productivity and entertainment..",
        thumbnail_1: Tablet3,
    },
    {
        id: 31,
        name: "MI Pad",
        original_price: 20000.00,
        current_price: 13000.00,
        discount: "16",
        category: "tablet",
        image: Tablet2,
        stock: "In Stock",
        feature_1: "13MP Camera",
        feature_2: "8720mAh Battery",
        feature_3: "Fast Chatging",
        features: {
            "display_size": "11 inches",
            "resolution": "2560 x 1600 pixels",
            "hdr_support": true,
            "processor": "Qualcomm Snapdragon 860",
            "ram": "6GB",
            "storage_options": "128GB, 256GB",
            "rear_camera": "13MP",
            "front_camera": "8MP",
            "connectivity": "Wi-Fi 5, Bluetooth 5.0",
            "battery_capacity": "8720mAh",
            "charging_speed": "22.5W Fast Charging",
          },
        additional_info: "The Xiaomi Pad 5 is a powerful and versatile tablet with an 11-inch WQHD+ display, offering a resolution of 2560 x 1600 pixels. The screen supports a 120Hz refresh rate and HDR10, making it perfect for watching videos, gaming, and productivity tasks with vibrant visuals and smooth transitions. Powered by the Qualcomm Snapdragon 860 processor, along with 6GB of RAM and 128GB or 256GB of storage options, the Pad 5 delivers fast and efficient performance for multitasking, gaming, and media consumption.The tablet comes with a 13MP rear camera and an 8MP front camera, ideal for video calls, capturing photos, and scanning documents. It supports quad speakers with Dolby Atmos, providing an immersive audio experience for media playback. Connectivity options include Wi-Fi 5 and Bluetooth 5.0, ensuring fast wireless connections. The Xiaomi Pad 5 has a large 8720mAh battery, supporting 22.5W fast charging, offering excellent battery life for extended usage. With a sleek, premium design and running MIUI for Pad based on Android, it is priced at around $400, offering a great balance of productivity and entertainment..",
        thumbnail_1: Tablet2,
    },
    {
        id: 30,
        name: "Xiaomi Pad 6",
        original_price: 37000.00,
        current_price: 33000.00,
        discount: "7",
        category: "tablet",
        image: Tablet1,
        stock: "In Stock",
        feature_1: "11 Inches",
        feature_2: "6GB RAM",
        feature_3: "120Hz Refresh Rate",
        features: {
            "display_size": "11 inches",
            "resolution": "2560 x 1600 pixels",
            "hdr_support": true,
            "processor": "Qualcomm Snapdragon 860",
            "ram": "6GB",
            "storage_options": "128GB, 256GB",
            "rear_camera": "13MP",
            "front_camera": "8MP",
            "connectivity": "Wi-Fi 5, Bluetooth 5.0",
            "battery_capacity": "8720mAh",
            "charging_speed": "22.5W Fast Charging",
          },
        additional_info: "The Xiaomi Pad 5 is a powerful and versatile tablet with an 11-inch WQHD+ display, offering a resolution of 2560 x 1600 pixels. The screen supports a 120Hz refresh rate and HDR10, making it perfect for watching videos, gaming, and productivity tasks with vibrant visuals and smooth transitions. Powered by the Qualcomm Snapdragon 860 processor, along with 6GB of RAM and 128GB or 256GB of storage options, the Pad 5 delivers fast and efficient performance for multitasking, gaming, and media consumption.The tablet comes with a 13MP rear camera and an 8MP front camera, ideal for video calls, capturing photos, and scanning documents. It supports quad speakers with Dolby Atmos, providing an immersive audio experience for media playback. Connectivity options include Wi-Fi 5 and Bluetooth 5.0, ensuring fast wireless connections. The Xiaomi Pad 5 has a large 8720mAh battery, supporting 22.5W fast charging, offering excellent battery life for extended usage. With a sleek, premium design and running MIUI for Pad based on Android, it is priced at around $400, offering a great balance of productivity and entertainment..",
        thumbnail_1: Tablet1,
    },
    {
        id: 29,
        name: "Mi TV",
        original_price: 47000.00,
        current_price: 44000.00,
        discount: "7",
        category: "screen",
        image: XiaomiTv5,
        stock: "In Stock",
        feature_1: "Smart",
        feature_2: "4K Ultra HD",
        features: {
            "display_size": "55 inches",
            "resolution": "4K Ultra HD",
            "operating_system": "Android TV 9.0",
            "processor": "Quad-core Cortex-A53",
            "ram": "2GB",
            "storage": "8GB",
            "audio_technology": "Dolby Audio, DTS-HD",
            "refresh_rate": "60Hz",
            "connectivity": "Wi-Fi, Bluetooth 4.2",
            "ports": "3 HDMI, 2 USB, Ethernet",
            "content_providers": "Netflix, Prime Video, Disney+ Hotstar, YouTube",
          },
        additional_info: "The Xiaomi Mi TV 4X, with its 55-inch 4K Ultra HD display, provides stunning picture clarity and vibrant colors, making it an ideal choice for home entertainment. Powered by Android TV 9.0, it offers seamless access to popular streaming services like Netflix, Prime Video, Disney+ Hotstar, and YouTube. The TV's performance is driven by a Quad-core Cortex-A53 processor and a Mali-450 GPU, complemented by 2GB of RAM and 8GB of internal storage, ensuring smooth operation for apps and media. For sound, the Mi TV 4X features 20W stereo speakers with Dolby Audio and DTS-HD support, delivering immersive audio. Connectivity options include Wi-Fi, Bluetooth 4.2, three HDMI ports, two USB ports, and Ethernet, allowing for versatile usage with various devices. The Bluetooth remote control, equipped with voice commands via Google Assistant, makes it easy to navigate and control the TV. With a 60Hz refresh rate and a sleek design, the Mi TV 4X offers excellent value at a competitive price of $400, making it a great option for anyone looking for a smart TV with powerful features.",
        thumbnail_1: XiaomiTv5,
    },
    {
        id: 28,
        name: "Xiaomi TV S",
        original_price: 55000.00,
        current_price: 50000.00,
        discount: "5",
        category: "screen",
        image: XiaomiTv4,
        stock: "In Stock",
        feature_1: "1GB RAM",
        feature_2: "8GB Storage",
        features: {
            "display_size": "43 inches",
            "resolution": "Full HD",
            "operating_system": "Android TV 9.0",
            "processor": "Quad-core Cortex-A53",
            "gpu": "Mali-450",
            "ram": "1GB",
            "storage": "8GB",
            "refresh_rate": "60Hz",
            "connectivity": "Wi-Fi, Bluetooth 4.2",
            "ports": "2 HDMI, 1 USB",

          }
          ,
        additional_info: "The Xiaomi Mi TV 4A, with its 43-inch Full HD display, offers a crisp and clear viewing experience, perfect for smaller rooms or budget-conscious buyers. Running on Android TV 9.0, it gives users access to popular streaming platforms like Netflix, Prime Video, Disney+ Hotstar, and YouTube, making it a versatile entertainment hub. The TV is powered by a Quad-core Cortex-A53 processor and Mali-450 GPU, along with 1GB of RAM and 8GB of internal storage, providing decent performance for streaming apps and basic functions.Audio is delivered through its 20W stereo speakers, supported by DTS-HD sound technology, ensuring good sound quality for everyday use. The Mi TV 4A comes equipped with essential connectivity options, including Wi-Fi, Bluetooth 4.2, two HDMI ports, and one USB port. Its Bluetooth remote control features voice commands through Google Assistant, making navigation easy and convenient. With a 60Hz refresh rate and a slim, modern design, the Xiaomi Mi TV 4A combines affordability and functionality, priced at around $250, making it an appealing option for those seeking a reliable smart TV experience at an affordable price.",
        thumbnail_1: XiaomiTv4,
    },
    {
        id: 27,
        name: "Mi TV 4A",
        original_price: 35000.00,
        current_price: 30000.00,
        discount: "8",
        category: "screen",
        image: XiaomiTv2,
        stock: "In Stock",
        feature_1: "43 inches | Smart",
        feature_2: "Full HD",
        features: {
            "display_size": "43 inches",
            "resolution": "Full HD",
            "operating_system": "Android TV 9.0",
            "processor": "Quad-core Cortex-A53",
            "gpu": "Mali-450",
            "ram": "1GB",
            "storage": "8GB",
            "refresh_rate": "60Hz",
            "connectivity": "Wi-Fi, Bluetooth 4.2",
            "ports": "2 HDMI, 1 USB",

          }
          ,
        additional_info: "The Xiaomi Mi TV 4A, with its 43-inch Full HD display, offers a crisp and clear viewing experience, perfect for smaller rooms or budget-conscious buyers. Running on Android TV 9.0, it gives users access to popular streaming platforms like Netflix, Prime Video, Disney+ Hotstar, and YouTube, making it a versatile entertainment hub. The TV is powered by a Quad-core Cortex-A53 processor and Mali-450 GPU, along with 1GB of RAM and 8GB of internal storage, providing decent performance for streaming apps and basic functions.Audio is delivered through its 20W stereo speakers, supported by DTS-HD sound technology, ensuring good sound quality for everyday use. The Mi TV 4A comes equipped with essential connectivity options, including Wi-Fi, Bluetooth 4.2, two HDMI ports, and one USB port. Its Bluetooth remote control features voice commands through Google Assistant, making navigation easy and convenient. With a 60Hz refresh rate and a slim, modern design, the Xiaomi Mi TV 4A combines affordability and functionality, priced at around $250, making it an appealing option for those seeking a reliable smart TV experience at an affordable price.",
        thumbnail_1: XiaomiTv2,
    },
    {
        id: 26,
        name: "Xiaomi Mi TV",
        original_price: 55000.00,
        current_price: 45000.00,
        discount: "10",
        category: "screen",
        image: XiaomiTv1,
        stock: "In Stock",
        feature_1: "55 inches | Smart",
        feature_2: "4K Ultra HD",
        features: {
            "display_size": "55 inches",
            "resolution": "4K Ultra HD",
            "operating_system": "Android TV 9.0",
            "processor": "Quad-core Cortex-A53",
            "ram": "2GB",
            "storage": "8GB",
            "audio_technology": "Dolby Audio, DTS-HD",
            "refresh_rate": "60Hz",
            "connectivity": "Wi-Fi, Bluetooth 4.2",
            "ports": "3 HDMI, 2 USB, Ethernet",
            "content_providers": "Netflix, Prime Video, Disney+ Hotstar, YouTube",
          },
        additional_info: "The Xiaomi Mi TV 4X, with its 55-inch 4K Ultra HD display, provides stunning picture clarity and vibrant colors, making it an ideal choice for home entertainment. Powered by Android TV 9.0, it offers seamless access to popular streaming services like Netflix, Prime Video, Disney+ Hotstar, and YouTube. The TV's performance is driven by a Quad-core Cortex-A53 processor and a Mali-450 GPU, complemented by 2GB of RAM and 8GB of internal storage, ensuring smooth operation for apps and media. For sound, the Mi TV 4X features 20W stereo speakers with Dolby Audio and DTS-HD support, delivering immersive audio. Connectivity options include Wi-Fi, Bluetooth 4.2, three HDMI ports, two USB ports, and Ethernet, allowing for versatile usage with various devices. The Bluetooth remote control, equipped with voice commands via Google Assistant, makes it easy to navigate and control the TV. With a 60Hz refresh rate and a sleek design, the Mi TV 4X offers excellent value at a competitive price of $400, making it a great option for anyone looking for a smart TV with powerful features.",
        thumbnail_1: XiaomiTv1,
    },
    {
        id: 19,
        name: "Mi Dual port Car",
        original_price: 4500.00,
        current_price: 3500.00,
        discount: "22",
        category: "accessory",
        image: MiCarCharger2,
        stock: "In Stock",
        features: {
            "FastCharging": "27W MAX",
            "DualPortOutput": "37W MAX",
            "SafetyFeatures": "Multiple protections",
            "Compatibility": "Compatible with mainstream models",
            "Design": "Streamlined black matte body",
          }
          ,
        additional_info: "The Mi Buds 3 Pro are advanced wireless earbuds that deliver an impressive audio experience with the convenience of Bluetooth 5.2 connectivity. Designed for both music lovers and those who frequently take calls, these earbuds offer a seamless connection with a reliable range of up to 10 meters in open spaces.Charging the earbuds is quick and efficient, requiring only approximately 1 hour for a full charge. The charging case takes around 2.5 hours to recharge using wired charging, providing the added benefit of portability and convenience.In terms of performance, the Mi Buds 3 Pro offer approximately 3 hours of call duration with noise cancellation off and at 50% volume, making them ideal for long conversations. For music enthusiasts, the earbuds deliver around 6 hours of playback time under the same conditions, allowing for extended listening sessions without interruptions.When not in use, the Mi Buds 3 Pro can stay in standby mode for up to 28 hours, making them an excellent companion for travel and daily commutes. With their blend of performance, comfort, and modern design, the Mi Buds 3 Pro are perfect for anyone looking to enhance their audio experience while on the go.The Mi Dual Port Car Charger is a versatile charging solution designed for on-the-go users who require efficient power delivery while driving. This charger supports 27W MAX fast flash charging through a single port, ensuring that your devices receive a quick and efficient charge, perfect for urgent power needs. Additionally, it features dual port output with a maximum capacity of 37W, allowing you to charge multiple devices simultaneously without compromising on speed.Safety is a key focus of the Mi Dual Port Car Charger, which includes multiple protections to safeguard against overcharging and overheating, providing peace of mind during use. The charger is equipped with a ring LED power indicator that clearly indicates the charging status and the location of the interface, making it easy to see even in low-light conditions.Designed with compatibility in mind, this charger works seamlessly with mainstream models of smartphones and other devices, making it a versatile addition to your tech accessories. The sleek, streamlined black matte body not only looks stylish but also complements modern vehicle interiors. Additionally, the charger features a positive and negative anti-skid shrapnel design, ensuring a secure connection and preventing slippage during use.",
        thumbnail_1: MiCarCharger1,
        thumbnail_3: MiCarCharger3,
    },
    {
        id: 14,
        name: "Mi Buds 3 Lite",
        original_price: 9000.00,
        current_price: 6500.00,
        discount: "28",
        category: "audio",
        image: MiBuds1,
        stock: "In Stock",
        features: {
            "WirelessConnection": "Bluetooth 5.2",
            "CommunicationRange": "10m (open space free of obstacles)",
            "DustWaterResistance": "IP54",
            "EarbudBatteryLife": "Approx. 5 hours",
            "ChargingCaseBatteryLife": "Approx. 18 hours",
            "EarbudDimensions": "24.5 x 16.7 x 24.6 mm",
            "ChargingCaseDimensions": "60 x 46 x 23.7 mm",
            "ChargingPort": "Type-C",
            "SingleEarbudWeight": "Approx. 4.2g",
            "TotalWeightWithChargingCase": "Approx. 36g"
          },
        additional_info: "The Mi Buds 3 Lite offer a reliable and high-quality audio experience with a Bluetooth 5.2 wireless connection, ensuring stable performance and low latency. With a communication range of up to 10 meters in open spaces, these earbuds provide freedom of movement without losing connectivity. They feature an IP54 rating, making them resistant to dust and splashes, perfect for workouts or daily use in different environments.The earbuds themselves have a battery life of approximately 5 hours, while the charging case extends this to a total of 18 hours of listening time, ensuring you can enjoy your music all day long. The earbuds are compact, with dimensions of 24.5 x 16.7 x 24.6 mm, and weigh just 4.2g each, making them lightweight and comfortable to wear. The charging case is also small and portable, measuring 60 x 46 x 23.7 mm, and comes with a Type-C charging port for fast charging. Overall, with a total weight of 36g (including the case), the Mi Buds 3 Lite provide a perfect blend of portability, durability, and performance.",
        thumbnail_1: MiBuds1,
        thumbnail_2: MiBuds2,
    },
    {
        id: 25,
        name: "Mi Smart Band 6",
        original_price: 8500.00,
        current_price: 5000.00,
        discount: "16",
        category: "watch",
        image: MiBand6,
        stock: "In Stock",
        features: {
            "ProductName": "Smart W12 IMILAB Watch",
            "Screen": "1.32 inch HD",
            "HeartRateMonitor": "24 Hours",
            "BatteryLife": "30 Days",
            "WaterResistance": "IP68",
            "CustomizableWatchFace": true,
            "Color": "Black"
        },
        additional_info: "The Smart W12 IMILAB Watch is a feature-rich smartwatch designed for users seeking a blend of style and functionality. It features a vibrant 1.32-inch HD screen that provides clear visuals for notifications, fitness tracking, and more. With a 24-hour heart rate monitor, this watch continuously tracks your heart rate, helping you keep an eye on your cardiovascular health throughout the day.One of its standout features is the impressive 30 days of battery life, allowing users to enjoy the watch's capabilities without frequent charging. This is complemented by its IP68 waterproof rating, making it resistant to dust and capable of withstanding immersion in water, which is perfect for workouts and outdoor activities.Additionally, the Smart W12 IMILAB Watch offers a customizable watch face, allowing users to personalize their display to match their style or mood. Available in a sleek black color, this smartwatch seamlessly combines aesthetic appeal with practical features, making it an ideal companion for both fitness enthusiasts and everyday users.",
        thumbnail_1: MiBand6,
    },
    {
        id: 13,
        name: "Xiaomi Smart Band 9",
        original_price: 8500.00,
        current_price: 7500.00,
        discount: "12",
        category: "watch",
        image: XiaomiWatch3,
        stock: "In Stock",
        features: {
            "Size": "46.53 x 21.63 x 10.95 mm",
            "Display": "AMOLED, 1.62 inches",
            "Weight": "15.8g",
            "SportsModes": "150+",
            "Colorways": "Midnight Black, Glacier Silver, Mystic Rose, Arctic Blue",
            "Connectivity": "Bluetooth 5.4",
            "Battery": "233mAh"
        },
        additional_info: "The Xiaomi Smart Band 9 is a sleek and feature-packed fitness tracker designed for users seeking style, functionality, and performance. It boasts a compact design, with dimensions of 46.53 x 21.63 x 10.95 mm and a lightweight build of just 15.8g, making it comfortable to wear all day. The device features a stunning AMOLED display measuring 1.62 inches, delivering vibrant colors and crisp details. With over 150 sports modes, the Smart Band 9 caters to fitness enthusiasts, offering comprehensive tracking for various activities. It supports Bluetooth 5.4 for seamless connectivity with smartphones and other devices, while its 233mAh battery provides long-lasting power. Available in stylish colorways such as Midnight Black, Glacier Silver, Mystic Rose, and Arctic Blue, the band blends fashion with functionality, making it an ideal choice for fitness-conscious users.",
        thumbnail_1: XiaomiWatch1,
        thumbnail_2: XiaomiWatch2,
        thumbnail_3: XiaomiWatch3,
    },
    {
        id: 24,
        name: "Mi Smart Band 7",
        original_price: 9500.00,
        current_price: 6000.00,
        discount: "14",
        category: "watch",
        image: MiBand7,
        stock: "In Stock",
        features: {
            "ProductName": "Smart W12 IMILAB Watch",
            "Screen": "1.32 inch HD",
            "HeartRateMonitor": "24 Hours",
            "BatteryLife": "30 Days",
            "WaterResistance": "IP68",
            "CustomizableWatchFace": true,
            "Color": "Black"
        },
        additional_info: "The Smart W12 IMILAB Watch is a feature-rich smartwatch designed for users seeking a blend of style and functionality. It features a vibrant 1.32-inch HD screen that provides clear visuals for notifications, fitness tracking, and more. With a 24-hour heart rate monitor, this watch continuously tracks your heart rate, helping you keep an eye on your cardiovascular health throughout the day.One of its standout features is the impressive 30 days of battery life, allowing users to enjoy the watch's capabilities without frequent charging. This is complemented by its IP68 waterproof rating, making it resistant to dust and capable of withstanding immersion in water, which is perfect for workouts and outdoor activities.Additionally, the Smart W12 IMILAB Watch offers a customizable watch face, allowing users to personalize their display to match their style or mood. Available in a sleek black color, this smartwatch seamlessly combines aesthetic appeal with practical features, making it an ideal companion for both fitness enthusiasts and everyday users.",
        thumbnail_1: MiBand7,
    },
    {
        id: 23,
        name: "Mi WIFI Repeater",
        current_price: 4500,
        category: "accessory",
        image: MiRepeater1,
        stock: "In Stock",
        features: {
            "ProductName": "Mi WiFi Repeater",
            "Antennas": "Two high-gain external antennas",
            "Compatibility": "Compatible with other brands of routers",
            "TransmissionRate": "300Mbps",
            "SupportedDevices": "Up to 64 devices",
            "NetworkManagement": "Xiaomi Mi WiFi App",
            "AutoUpgrade": "Automatic upgrade without manual settings",
            "PlugAndPlay": "Plug and play, easy to use"
        },
        additional_info: "The Mi WiFi Repeater is designed to extend the range and improve the performance of your wireless network with its powerful features. It comes equipped with two high-gain external antennas that offer wider coverage, ensuring that you can enjoy a stronger and more stable wireless connection across larger areas. This makes it ideal for homes, offices, or other spaces where a strong WiFi signal is needed.One of the standout features is its compatibility with routers from other brands, making it a flexible solution for users who want to extend their existing wireless networks without worrying about compatibility issues. The transmission rate of 300Mbps ensures fast and reliable data transfer, allowing for smooth streaming, gaming, and browsing.The repeater can support up to 64 devices simultaneously, making it a great option for households or businesses with multiple connected devices, such as smartphones, tablets, laptops, and smart home appliances.The Xiaomi Mi WiFi App allows you to easily manage your network settings, providing a user-friendly interface for monitoring and adjusting your connection. Additionally, the repeater features an automatic upgrade function, ensuring that its firmware stays up-to-date without requiring manual intervention.",
        thumbnail_1: MiRepeater1,
        thumbnail_3: MiRepeater2,
    },
    {
        id: 22,
        name: "Mi True Wireless ",
        original_price: 6500.00,
        current_price: 4500.00,
        discount: "14",
        category: "audio",
        image: WirelessBuds1,
        stock: "In Stock",
        features: {
            "ProductName": "Mi True Wireless Earbuds",
            "WirelessConnection": "Bluetooth 5.0",
            "CommunicationDistance": "10 meters",
            "ListeningTime": "About 4 hours",
            "StandbyTime": "About 150 hours",
            "SingleEarphoneBatteryCapacity": "43mAh",
            "ChargingBoxBatteryCapacity": "300mAh",
            "HeadphoneChargingTime": "About 1.5 hours",
            "ChargingBoxChargingTime": "About 2 hours",
            "SingleEarphoneWeight": "4.1g",
            "TotalWeightWithChargingBox": "35.4g",
            "ChargingBoxSize": "62×40×27.2mm",
            "HeadphoneSize": "26.65×16.4×21.6mm"
        },
        additional_info: "The Mi True Wireless Earbuds are a lightweight, compact, and high-performance pair of wireless earbuds designed to offer an immersive audio experience. Featuring Bluetooth 5.0 technology, they provide seamless connectivity with minimal lag and stable audio transmission across devices. The earbuds support popular Bluetooth protocols such as HFP, A2DP, HSP, and AVRCP, allowing them to work efficiently with a wide range of smartphones, tablets, and laptops.With a communication distance of up to 10 meters in open spaces, you can enjoy wireless freedom without worrying about losing connection. Each earbud offers a continuous listening time of about 4 hours, making them perfect for workouts, commutes, or casual listening sessions. Additionally, the standby time extends up to 150 hours, ensuring they are ready to use when needed.The battery capacity of each earbud is 43mAh, while the charging case has a 300mAh battery, providing extra charges on the go. The earbuds take approximately 1.5 hours to fully charge, and the charging case takes around 2 hours to recharge. Together, the earbuds and case weigh only 35.4g, with the earbuds alone weighing 4.1g, making them extremely lightweight and portable.The charging case measures 62×40×27.2mm, and the earbuds have a compact size of 26.65×16.4×21.6mm, ensuring a snug fit in your ears while still being easy to store and carry. These features make the Mi True Wireless Earbuds an ideal choice for users looking for a blend of convenience, portability, and quality audio performance.",
        thumbnail_1: WirelessBuds1,
        thumbnail_3: WirelessBuds2,
    },
    {
        id: 13,
        name: "Xiaomi Smart Band 9",
        original_price: 8500.00,
        current_price: 7500.00,
        discount: "12",
        category: "watch",
        image: XiaomiWatch2,
        stock: "In Stock",
        features: {
            "Size": "46.53 x 21.63 x 10.95 mm",
            "Display": "AMOLED, 1.62 inches",
            "Weight": "15.8g",
            "SportsModes": "150+",
            "Colorways": "Midnight Black, Glacier Silver, Mystic Rose, Arctic Blue",
            "Connectivity": "Bluetooth 5.4",
            "Battery": "233mAh"
        },
        additional_info: "The Xiaomi Smart Band 9 is a sleek and feature-packed fitness tracker designed for users seeking style, functionality, and performance. It boasts a compact design, with dimensions of 46.53 x 21.63 x 10.95 mm and a lightweight build of just 15.8g, making it comfortable to wear all day. The device features a stunning AMOLED display measuring 1.62 inches, delivering vibrant colors and crisp details. With over 150 sports modes, the Smart Band 9 caters to fitness enthusiasts, offering comprehensive tracking for various activities. It supports Bluetooth 5.4 for seamless connectivity with smartphones and other devices, while its 233mAh battery provides long-lasting power. Available in stylish colorways such as Midnight Black, Glacier Silver, Mystic Rose, and Arctic Blue, the band blends fashion with functionality, making it an ideal choice for fitness-conscious users.",
        thumbnail_1: XiaomiWatch1,
        thumbnail_2: XiaomiWatch2,
        thumbnail_3: XiaomiWatch3,
    },
    {
        id: 21,
        name: "Mi Power Bank Compact",
        original_price: 7500.00,
        current_price: 3500.00,
        discount: "22",
        category: "accessory",
        image: MiCompact1,
        stock: "In Stock",
        features: {
            "ProductName": "Mi Power Bank Compact",
            "BatteryType": "Lithium Polymer Battery",
            "Capacity": "10000mAh 3.7V (37Wh)",
            "MaxOutputPower": "22.5W",
            "OperatingTemperature": "0°C ~ 40°C",
            "InputPorts": "Micro-USB, USB-C",
            "QuickCharge": "3.0 + PD",
            "Dimensions": "90 x 63.9 x 24.4 mm",
            "Weight": "200 grams"
          },
        additional_info: "The Mi Power Bank Compact is a portable and reliable power solution designed for users on the go. With a 10000mAh lithium polymer battery, it offers a robust capacity, providing multiple charges for smartphones, tablets, and other devices. The power bank supports a maximum output of 22.5W, ensuring fast and efficient charging, even for power-hungry devices.Equipped with multiple input and output ports, including Micro-USB, USB-C, and dual USB-A ports, it offers great versatility for charging different devices. The USB-C port can output 5V 3A, providing quick and efficient charging, while the USB-A port supports various voltage levels, including 5V, 9V, and 12V for different charging needs.The power bank is compatible with Quick Charge 3.0 and Power Delivery (PD) technologies, ensuring faster recharge times for both the power bank and connected devices. Its compact dimensions of 90 x 63.9 x 24.4 mm and lightweight build at 200 grams make it easy to carry in your pocket or bag, perfect for daily use.Designed to operate within a temperature range of 0°C to 40°C, the Mi Power Bank Compact is suitable for a variety of environments. With its multi-port design and high capacity, it is an excellent option for users looking for a portable, fast-charging power bank to keep their devices powered throughout the day.",
        thumbnail_1: MiCompact1,
        thumbnail_3: MiCompact3,
    },
    {
        id: 20,
        name: "Mi In-Ear Headphones",
        current_price: 3500.00,
        category: "audio",
        image: MiEarphones1,
        stock: "In Stock",
        features: {
            "Type": "In-Ear",
            "DriverSize": "10mm",
            "FrequencyResponse": "20Hz - 20kHz",
            "Impedance": "32Ω",
            "Sensitivity": "98dB",
            "Microphone": "Yes",
            "CableLength": "1.25m",
            "Connector": "3.5mm",
            "Weight": "Approx. 14g",
          }
          ,
        additional_info: "The Mi In-Ear Headphones are designed for music enthusiasts who seek quality sound and comfort in a compact form factor. These in-ear headphones come equipped with 10mm drivers, delivering a rich audio experience across a frequency range of 20Hz to 20kHz, making them suitable for various genres of music.With an impedance of 32Ω and a sensitivity of 98dB, these headphones provide clear and balanced sound, ensuring that you can enjoy your favorite tracks with minimal distortion. The 1.25m cable length is optimal for everyday use, and the 3.5mm connector ensures compatibility with a wide range of devices, including smartphones, tablets, and laptops.Designed for convenience, the Mi In-Ear Headphones feature a built-in microphone for hands-free calling, as well as a remote control for easy access to playback controls. The tangle-free cable and comfortable ear tips enhance the user experience, allowing for prolonged listening without discomfort.With their lightweight design, weighing approximately 14g, and noise isolation features, the Mi In-Ear Headphones are perfect for daily commutes, workouts, or simply relaxing at home. Available in a sleek black color, they combine style with functionality, making them a great choice for anyone looking to elevate their audio experience on the go.",
        thumbnail_1: MiEarphones1,
        thumbnail_2: MiEarphones2,
        thumbnail_3: MiEarphones3,
    },
    {
        id: 19,
        name: "Mi Dual port Car",
        original_price: 4500.00,
        current_price: 3500.00,
        discount: "22",
        category: "accessory",
        image: MiCarCharger1,
        stock: "In Stock",
        features: {
            "FastCharging": "27W MAX",
            "DualPortOutput": "37W MAX",
            "SafetyFeatures": "Multiple protections",
            "Compatibility": "Compatible with mainstream models",
            "Design": "Streamlined black matte body",
          }
          ,
        additional_info: "The Mi Buds 3 Pro are advanced wireless earbuds that deliver an impressive audio experience with the convenience of Bluetooth 5.2 connectivity. Designed for both music lovers and those who frequently take calls, these earbuds offer a seamless connection with a reliable range of up to 10 meters in open spaces.Charging the earbuds is quick and efficient, requiring only approximately 1 hour for a full charge. The charging case takes around 2.5 hours to recharge using wired charging, providing the added benefit of portability and convenience.In terms of performance, the Mi Buds 3 Pro offer approximately 3 hours of call duration with noise cancellation off and at 50% volume, making them ideal for long conversations. For music enthusiasts, the earbuds deliver around 6 hours of playback time under the same conditions, allowing for extended listening sessions without interruptions.When not in use, the Mi Buds 3 Pro can stay in standby mode for up to 28 hours, making them an excellent companion for travel and daily commutes. With their blend of performance, comfort, and modern design, the Mi Buds 3 Pro are perfect for anyone looking to enhance their audio experience while on the go.The Mi Dual Port Car Charger is a versatile charging solution designed for on-the-go users who require efficient power delivery while driving. This charger supports 27W MAX fast flash charging through a single port, ensuring that your devices receive a quick and efficient charge, perfect for urgent power needs. Additionally, it features dual port output with a maximum capacity of 37W, allowing you to charge multiple devices simultaneously without compromising on speed.Safety is a key focus of the Mi Dual Port Car Charger, which includes multiple protections to safeguard against overcharging and overheating, providing peace of mind during use. The charger is equipped with a ring LED power indicator that clearly indicates the charging status and the location of the interface, making it easy to see even in low-light conditions.Designed with compatibility in mind, this charger works seamlessly with mainstream models of smartphones and other devices, making it a versatile addition to your tech accessories. The sleek, streamlined black matte body not only looks stylish but also complements modern vehicle interiors. Additionally, the charger features a positive and negative anti-skid shrapnel design, ensuring a secure connection and preventing slippage during use.",
        thumbnail_1: MiCarCharger1,
        thumbnail_3: MiCarCharger3,
    },
    {
        id: 18,
        name: "Mi Buds 3 Pro",
        current_price: 17000.00,
        category: "audio",
        image: MiBuds31,
        stock: "In Stock",
        features: {
            "ProductName": "Mi Buds 3 Pro",
            "WirelessConnection": "Bluetooth 5.2",
            "EarbudsChargeTime": "Approx. 1 hour",
            "ChargingCaseChargeTime": "Approx. 2.5 hours",
            "CallDuration": "Approx. 3 hours",
            "CommunicationRange": "10m",
            "MusicPlaybackTime": "Approx. 6 hours",
            "StandbyTime": "Approx. 28 hours"
          },
        additional_info: "The Mi Buds 3 Pro are advanced wireless earbuds that deliver an impressive audio experience with the convenience of Bluetooth 5.2 connectivity. Designed for both music lovers and those who frequently take calls, these earbuds offer a seamless connection with a reliable range of up to 10 meters in open spaces.Charging the earbuds is quick and efficient, requiring only approximately 1 hour for a full charge. The charging case takes around 2.5 hours to recharge using wired charging, providing the added benefit of portability and convenience.In terms of performance, the Mi Buds 3 Pro offer approximately 3 hours of call duration with noise cancellation off and at 50% volume, making them ideal for long conversations. For music enthusiasts, the earbuds deliver around 6 hours of playback time under the same conditions, allowing for extended listening sessions without interruptions.When not in use, the Mi Buds 3 Pro can stay in standby mode for up to 28 hours, making them an excellent companion for travel and daily commutes. With their blend of performance, comfort, and modern design, the Mi Buds 3 Pro are perfect for anyone looking to enhance their audio experience while on the go.",
        thumbnail_1: MiBuds31,
        thumbnail_2: MiBuds32,
    },
    {
        id: 17,
        name: "Mi Power Bank 3",
        original_price: 0.00,
        current_price: 5500.00,
        category: "accessory",
        image: PowerBank1,
        stock: "Limited",
        features: {
            "ProductName": "Mi 10000mAh Power Bank 3",
            "BatteryCapacity": "10000 mAh",
            "FastCharging": true,
            "Weight": "200g",
            "Dimensions": "147 x 71.2 x 14.2 mm",
            "Color": "Black",
          },
        additional_info: "The Mi 10000mAh Power Bank 3 is a compact and powerful charging solution designed to keep your devices powered up on the go. With a battery capacity of 10000mAh, it offers ample charge for smartphones, tablets, and other devices, ensuring you stay connected throughout the day.This power bank features multiple input ports, including MicroUSB and Type-C, both capable of fast charging at 5V/2A, allowing for quick recharging of the power bank itself. It also comes equipped with multiple output ports, including two USB-A ports that support 5V/2.4A each and a Type-C port that can deliver 5V/3A, enabling simultaneous charging of multiple devices.Weighing just 200g and measuring 147 x 71.2 x 14.2 mm, the Mi Power Bank 3 is lightweight and portable, making it easy to carry in your bag or pocket. Available in a sleek black color, it combines style with practicality.Safety is a top priority, and this power bank is equipped with various protection features, including overcharge protection, over-discharge protection, short circuit protection, and temperature protection, ensuring safe and reliable charging. Overall, the Mi 10000mAh Power Bank 3 is an essential accessory for anyone needing reliable power on the go",
        thumbnail_1: PowerBank1,
        thumbnail_2: PowerBank2,
    },
    {
        id: 16,
        name: "Smart W12 IMILAB",
        original_price: 9500.00,
        current_price: 7500.00,
        discount: "11",
        category: "watch",
        image: WatchW1,
        stock: "In Stock",
        features: {
            "ProductName": "Smart W12 IMILAB Watch",
            "Screen": "1.32 inch HD",
            "HeartRateMonitor": "24 Hours",
            "BatteryLife": "30 Days",
            "WaterResistance": "IP68",
            "CustomizableWatchFace": true,
            "Color": "Black"
        },
        additional_info: "The Smart W12 IMILAB Watch is a feature-rich smartwatch designed for users seeking a blend of style and functionality. It features a vibrant 1.32-inch HD screen that provides clear visuals for notifications, fitness tracking, and more. With a 24-hour heart rate monitor, this watch continuously tracks your heart rate, helping you keep an eye on your cardiovascular health throughout the day.One of its standout features is the impressive 30 days of battery life, allowing users to enjoy the watch's capabilities without frequent charging. This is complemented by its IP68 waterproof rating, making it resistant to dust and capable of withstanding immersion in water, which is perfect for workouts and outdoor activities.Additionally, the Smart W12 IMILAB Watch offers a customizable watch face, allowing users to personalize their display to match their style or mood. Available in a sleek black color, this smartwatch seamlessly combines aesthetic appeal with practical features, making it an ideal companion for both fitness enthusiasts and everyday users.",
        thumbnail_1: WatchW1,
    },
    {
        id: 22,
        name: "Mi True Wireless ",
        original_price: 6500.00,
        current_price: 4500.00,
        discount: "14",
        category: "audio",
        image: WirelessBuds2,
        stock: "In Stock",
        features: {
            "ProductName": "Mi True Wireless Earbuds",
            "WirelessConnection": "Bluetooth 5.0",
            "CommunicationDistance": "10 meters",
            "ListeningTime": "About 4 hours",
            "StandbyTime": "About 150 hours",
            "SingleEarphoneBatteryCapacity": "43mAh",
            "ChargingBoxBatteryCapacity": "300mAh",
            "HeadphoneChargingTime": "About 1.5 hours",
            "ChargingBoxChargingTime": "About 2 hours",
            "SingleEarphoneWeight": "4.1g",
            "TotalWeightWithChargingBox": "35.4g",
            "ChargingBoxSize": "62×40×27.2mm",
            "HeadphoneSize": "26.65×16.4×21.6mm"
        },
        additional_info: "The Mi True Wireless Earbuds are a lightweight, compact, and high-performance pair of wireless earbuds designed to offer an immersive audio experience. Featuring Bluetooth 5.0 technology, they provide seamless connectivity with minimal lag and stable audio transmission across devices. The earbuds support popular Bluetooth protocols such as HFP, A2DP, HSP, and AVRCP, allowing them to work efficiently with a wide range of smartphones, tablets, and laptops.With a communication distance of up to 10 meters in open spaces, you can enjoy wireless freedom without worrying about losing connection. Each earbud offers a continuous listening time of about 4 hours, making them perfect for workouts, commutes, or casual listening sessions. Additionally, the standby time extends up to 150 hours, ensuring they are ready to use when needed.The battery capacity of each earbud is 43mAh, while the charging case has a 300mAh battery, providing extra charges on the go. The earbuds take approximately 1.5 hours to fully charge, and the charging case takes around 2 hours to recharge. Together, the earbuds and case weigh only 35.4g, with the earbuds alone weighing 4.1g, making them extremely lightweight and portable.The charging case measures 62×40×27.2mm, and the earbuds have a compact size of 26.65×16.4×21.6mm, ensuring a snug fit in your ears while still being easy to store and carry. These features make the Mi True Wireless Earbuds an ideal choice for users looking for a blend of convenience, portability, and quality audio performance.",
        thumbnail_1: WirelessBuds1,
        thumbnail_3: WirelessBuds2,
    },
    {
        id: 13,
        name: "Xiaomi Smart Band 9",
        original_price: 8500.00,
        current_price: 7500.00,
        discount: "12",
        category: "watch",
        image: XiaomiWatch1,
        stock: "In Stock",
        features: {
            "Size": "46.53 x 21.63 x 10.95 mm",
            "Display": "AMOLED, 1.62 inches",
            "Weight": "15.8g",
            "SportsModes": "150+",
            "Colorways": "Midnight Black, Glacier Silver, Mystic Rose, Arctic Blue",
            "Connectivity": "Bluetooth 5.4",
            "Battery": "233mAh"
        },
        additional_info: "The Xiaomi Smart Band 9 is a sleek and feature-packed fitness tracker designed for users seeking style, functionality, and performance. It boasts a compact design, with dimensions of 46.53 x 21.63 x 10.95 mm and a lightweight build of just 15.8g, making it comfortable to wear all day. The device features a stunning AMOLED display measuring 1.62 inches, delivering vibrant colors and crisp details. With over 150 sports modes, the Smart Band 9 caters to fitness enthusiasts, offering comprehensive tracking for various activities. It supports Bluetooth 5.4 for seamless connectivity with smartphones and other devices, while its 233mAh battery provides long-lasting power. Available in stylish colorways such as Midnight Black, Glacier Silver, Mystic Rose, and Arctic Blue, the band blends fashion with functionality, making it an ideal choice for fitness-conscious users.",
        thumbnail_1: XiaomiWatch1,
        thumbnail_2: XiaomiWatch2,
        thumbnail_3: XiaomiWatch3,
    },
    {
        id: 16,
        name: "Smart W12 IMILAB",
        original_price: 9500.00,
        current_price: 7500.00,
        discount: "11",
        category: "watch",
        image: WatchW1,
        stock: "In Stock",
        features: {
            "ProductName": "Smart W12 IMILAB Watch",
            "Screen": "1.32 inch HD",
            "HeartRateMonitor": "24 Hours",
            "BatteryLife": "30 Days",
            "WaterResistance": "IP68",
            "CustomizableWatchFace": true,
            "Color": "Black"
        },
        additional_info: "The Smart W12 IMILAB Watch is a feature-rich smartwatch designed for users seeking a blend of style and functionality. It features a vibrant 1.32-inch HD screen that provides clear visuals for notifications, fitness tracking, and more. With a 24-hour heart rate monitor, this watch continuously tracks your heart rate, helping you keep an eye on your cardiovascular health throughout the day.One of its standout features is the impressive 30 days of battery life, allowing users to enjoy the watch's capabilities without frequent charging. This is complemented by its IP68 waterproof rating, making it resistant to dust and capable of withstanding immersion in water, which is perfect for workouts and outdoor activities.Additionally, the Smart W12 IMILAB Watch offers a customizable watch face, allowing users to personalize their display to match their style or mood. Available in a sleek black color, this smartwatch seamlessly combines aesthetic appeal with practical features, making it an ideal companion for both fitness enthusiasts and everyday users.",
        thumbnail_1: WatchW1,
    },
    {
        id: 14,
        name: "Mi Buds 3 Lite",
        original_price: 9000.00,
        current_price: 6500.00,
        discount: "28",
        category: "audio",
        image: MiBuds1,
        stock: "In Stock",
        features: {
            "WirelessConnection": "Bluetooth 5.2",
            "CommunicationRange": "10m (open space free of obstacles)",
            "DustWaterResistance": "IP54",
            "EarbudBatteryLife": "Approx. 5 hours",
            "ChargingCaseBatteryLife": "Approx. 18 hours",
            "EarbudDimensions": "24.5 x 16.7 x 24.6 mm",
            "ChargingCaseDimensions": "60 x 46 x 23.7 mm",
            "ChargingPort": "Type-C",
            "SingleEarbudWeight": "Approx. 4.2g",
            "TotalWeightWithChargingCase": "Approx. 36g"
          },
        additional_info: "The Mi Buds 3 Lite offer a reliable and high-quality audio experience with a Bluetooth 5.2 wireless connection, ensuring stable performance and low latency. With a communication range of up to 10 meters in open spaces, these earbuds provide freedom of movement without losing connectivity. They feature an IP54 rating, making them resistant to dust and splashes, perfect for workouts or daily use in different environments.The earbuds themselves have a battery life of approximately 5 hours, while the charging case extends this to a total of 18 hours of listening time, ensuring you can enjoy your music all day long. The earbuds are compact, with dimensions of 24.5 x 16.7 x 24.6 mm, and weigh just 4.2g each, making them lightweight and comfortable to wear. The charging case is also small and portable, measuring 60 x 46 x 23.7 mm, and comes with a Type-C charging port for fast charging. Overall, with a total weight of 36g (including the case), the Mi Buds 3 Lite provide a perfect blend of portability, durability, and performance.",
        thumbnail_1: MiBuds1,
        thumbnail_2: MiBuds2,
    },
    {
        id: 15,
        name: "Mi TV Box S",
        original_price: 25000.00,
        current_price: 18500.00,
        discount: "15",
        category: "accessory",
        image: MiTv1,
        stock: "In Stock",
        features: {
            "OutputResolution": "4K (3840 x 2160)",
            "CPU": "Cortex-A53 Quad-core 64bit",
            "GPU": "Mali-450",
            "RAM": "2GB DDR3",
            "Storage": "8GB eMMC",
            "OperatingSystem": "Android 8.1",
            "WiFi": "802.11a/b/g/n/ac 2.4GHz/5GHz",
            "Bluetooth": "4.1",
            "Sockets": "HDMI2.0a, USB2.0, PowerInterface1, AudioOut",
        },
        additional_info: "The Mi TV Box S is a powerful and compact streaming device that supports 4K output resolution at 3840 x 2160, delivering stunning visual clarity for your media. Powered by a Cortex-A53 Quad-core 64bit CPU and a Mali-450 GPU, it ensures smooth performance for apps, streaming, and video playback. With 2GB of DDR3 RAM and 8GB of eMMC storage, users can enjoy a seamless experience while installing and running apps.Running on Android 8.1, the Mi TV Box S provides access to a wide range of Android apps, including popular streaming platforms, with smooth multitasking. It supports Wi-Fi (802.11a/b/g/n/ac) on both 2.4GHz and 5GHz bands for fast and stable connectivity. The device also includes Bluetooth 4.1 for connecting wireless accessories such as controllers and headphones.In terms of connectivity, the Mi TV Box S features essential sockets including one HDMI2.0a port for high-definition output, one USB2.0 port for connecting external devices, one power interface, and an audio out port for enhanced sound integration. The compact design and powerful capabilities make it an excellent choice for transforming any TV into a smart entertainment hub.",
        thumbnail_1: MiTv1,
        thumbnail_2: MiTv2,
    },
    {
        id: 1,
        name: "Redmi Note 13 8/256",
        original_price: 33000.00,
        current_price: 22300.00,
        discount: "12",
        category: "smartphone",
        image: RedmiNote131,
        stock: "In Stock",
        features: {"RAM": "6GB, 8GB", "colors": "Midnight Black, Mint Green, Ice Blue, Ocean Sunset", "battery": "5000mAh, 33W", "display": "6.67 inches, AMOLED, 120Hz", "processor": "Qualcomm SM6225 Snapdragon 685", "main_camera": "108MP + 8MP + 2MP", "connectivity": "Dual SIM, 3G, 4G, Wi-Fi", "front_camera": "16MP", "internal_storage": "128GB, 256GB", "operating_system": "Android 13, MIUI 14"},
        additional_info: "The Redmi Note 13 stands out with its high-resolution 108MP main camera, which is rare in this price category. It offers a versatile photography experience with additional 8MP ultra-wide and 2MP macro lenses, making it ideal for users who love capturing detailed photos. The phone excels in different lighting conditions, allowing for great shots, whether close-ups, wide-angle landscapes, or everyday scenes.The phone’s 6.67-inch AMOLED display with a 120Hz refresh rate provides a smooth and fluid user experience, whether for gaming, browsing, or media consumption. The AMOLED panel ensures vivid colors and deep contrasts, enhancing video playback quality and gaming visuals. The 120Hz refresh rate reduces motion blur, making interactions smoother and more responsive.Powered by the Qualcomm Snapdragon 685, this device guarantees fast and efficient performance. Whether running multiple apps or playing graphics-intensive games, the Snapdragon processor ensures a seamless experience without noticeable lag, making",
        thumbnail_1: RedmiNote131,
        thumbnail_2: RedmiNote133,
        slogan: "Master Light, Capture Night",
        feature_1: "108MP Camera",
        feature_2: "5000mAh Battery",
    },
    {
        id: 2,
        name: "Redmi A3 Pro",
        current_price: 12000.00,
        category: "smartphone",
        image: A3Pro,
        stock: "In Stock",
        features: {"OS": "Android 14, HyperOS", "Ram": "4GB RAM", "Colors": "Blue; other colors", "Battery": "5160mAh, 10W wired", "Display": "6.88-inch IPS LCD, 90Hz, 720 x 1640 pixels", "Internal": "128GB", "Processor": "Mediatek Helio G81 Ultra, Octa-core ", "Main_camera": "50 MP (wide)", "Connectivity": "LTE, Bluetooth 5.4, USB Type-C", "Front_camera": "Yes (selfie camera)"},
        additional_info: "The Redmi A3 Pro features a large 6.88-inch IPS LCD display with a smooth 90Hz refresh rate, providing an enhanced visual experience for scrolling and watching videos. With a resolution of 720 x 1640 pixels, the screen delivers vibrant colors and decent clarity, ensuring an enjoyable viewing experience.This smartphone is powered by the Mediatek Helio G81 Ultra chipset, which features an octa-core processor (comprising 2x2.0 GHz Cortex-A75 and 6x1.8 GHz Cortex-A55), paired with a capable 4GB RAM and 128GB of internal storage, utilizing eMMC 5.1 technology for efficient data handling. The dedicated microSDXC card slot allows for easy expansion, ensuring that users have ample storage for apps, photos, and videos.For photography, the Redmi A3 Pro boasts a 50 MP main camera, equipped with features like LED flash and HDR for capturing stunning photos. It supports 1080p video recording at 30fps, enabling users to document their moments in high definition. The selfie camera also supports 1080p video, ensuring clear and detailed video calls.The device is powered by a robust 5160mAh battery, providing ample life for day-to-day use, though it supports 10W wired charging, which means charging speeds may be relatively slow.In terms of connectivity, the Redmi A3 Pro covers all bases with support for GSM, HSPA, and LTE networks. It features Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.4, and NFC capabilities (depending on the market), making it versatile for various connectivity needs. Additionally, it includes a USB Type-C 2.0 port for charging and data transfer.Running on Android 14 with HyperOS, the phone provides a modern software experience with planned updates for future enhancements. With side-mounted fingerprint recognition, an accelerometer, and a compass, the phone offers practical features for security and navigation.",
        thumbnail_1: A3Pro,
        slogan: "Power On, Last Longer",
        feature_1: "5160 mAh, 10W Battery",
        feature_2: "4GB RAM 128GB Internal",
    },
    {
        id: 3,
        name: "Poco M6 Pro 12/512",
        original_price: 65000.00,
        current_price: 55000.00,
        discount: "10",
        category: "smartphone",
        image: PocoM6Pro3,
        stock: "In Stock",
        features: {"Ram": "12GB RAM", "Battery": "5000mAh, 67W", "Display": "6.67-inch AMOLED, 120Hz, 1080x2400px", "Internal": "512GB", "Main_camera": "64 MP (wide), 8 MP (ultra wide), 2 MP (macro)", "Connectivity": "LTE, Hybrid Dual SIM, Wi-Fi 5", "Front_camera": "16 MP (wide)"},
        additional_info: "The Poco M6 Pro boasts a stunning 6.67-inch AMOLED display with a smooth 120Hz refresh rate, perfect for fluid scrolling and gaming. The high brightness of up to 1300 nits ensures a clear view even under direct sunlight, while its 1080x2400px resolution delivers crisp visuals, making videos and images come to life.Under the hood, this device comes with two configurations of RAM—either 8GB or 12GB—and large internal storage options of 256GB or 512GB. With UFS 2.2 storage for faster data access and performance, it also supports expansion via a microSDXC card, providing ample room for all your media and apps.For photography enthusiasts, the Poco M6 Pro features a powerful 64 MP main camera, supported by an 8 MP ultra-wide sensor and a 2 MP macro lens, allowing you to capture a wide range of shots from sweeping landscapes to intricate close-ups. On the front, the 16 MP wide camera ensures sharp selfies and high-quality video calls.The 5000mAh battery keeps you powered throughout the day, and with its 67W wired charging, you can get to 100% in just 44 minutes, eliminating long charging wait times.In terms of connectivity, the Poco M6 Pro offers a comprehensive set of options including LTE, Wi-Fi 5, Bluetooth 5.2, NFC, and an infrared port. The inclusion of a 3.5mm headphone jack is a bonus for those who still prefer wired audio accessories. Whether you're gaming, working, or simply enjoying media, this phone provides a reliable and feature-packed experience.",
        thumbnail_1: PocoM6Pro1,
        thumbnail_2: PocoM6Pro3,
    },
    {
        id: 4,
        name: "Redmi 14C 6/128",
        original_price: 20000.00,
        current_price: 15300.00,
        discount: "15",
        category: "smartphone",
        image: Redmi14C2,
        stock: "Limited",
        features: {"ram": "6GB ", "colors": "Midnight Black, Sage Green, Dreamy Purple, Starry Blue", "battery": "5160 mAh, 18W", "display": "IPS LCD, 6.88 inches, 720 x 1640 pixels, 120Hz", "internal": "128GB", "processor": "Mediatek Helio G81 Ultra, Octa-core", "main_camera": "50 MP (wide), 2 MP (depth), 0.08 MP (auxiliary)", "front_camera": "13 MP"},
        additional_info: "The Redmi 14C, announced on August 30, 2024, combines a modern design with robust features, making it a competitive choice in the mid-range smartphone market. Its dimensions of 171.9 x 77.8 x 8.2 mm and a weight of approximately 204 to 211 grams contribute to a solid build quality, featuring a glass front, a plastic frame, and options for a glass back or eco-friendly silicone polymer back.This device supports dual SIM functionality (Nano-SIM, dual stand-by), providing users with the convenience of managing two phone numbers seamlessly.The 6.88-inch IPS LCD display boasts a resolution of 720 x 1640 pixels with a 120Hz refresh rate, enhancing the visual experience with smooth scrolling and vibrant colors. The display also offers a typical brightness of 450 nits, ensuring good visibility even in bright conditions.Powered by the Mediatek Helio G81 Ultra chipset, the Redmi 14C features an octa-core CPU that includes 2x2.0 GHz Cortex-A75 and 6x1.8 GHz Cortex-A55 cores, paired with the Mali-G52 MC2 GPU for efficient graphics performance. The phone comes with various internal storage options ranging from 128GB to 256GB, along with multiple RAM configurations (4GB, 6GB, or 8GB), supporting expandable storage through a microSDXC card slot.The camera system includes a dual main camera setup featuring a 50 MP wide lens and a 2 MP depth lens, complemented by an auxiliary lens. The camera supports features like HDR and can record videos at 1080p. For selfies, the front-facing camera offers a 13 MP sensor, also capable of 1080p video recording.The Redmi 14C is equipped with a 5160 mAh battery, supporting 18W wired charging, which allows for extended usage on a single charge. Connectivity options include Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.4, and a USB Type-C 2.0 port, alongside various positioning systems.",
        thumbnail_1: Redmi14C2,
        thumbnail_2: Redmi14C1,
    },
    {
        id: 5,
        name: "Redmi 14C 4/128",
        original_price: 17500.00,
        current_price: 13500.00,
        discount: "11",
        category: "smartphone",
        image: Redmi14C1,
        stock: "In Stock",
        features: {"ram": "4GB", "colors": "Midnight Black, Sage Green, Dreamy Purple, Starry Blue", "battery": "5160 mAh, 18W", "display": "IPS LCD, 6.88 inches, 720 x 1640 pixels, 120Hz", "internal": "128GB", "processor": "Mediatek Helio G81 Ultra, Octa-core", "main_camera": "50 MP (wide), 2 MP (depth), 0.08 MP (auxiliary)", "front_camera": "13 MP"},
        additional_info: "The Redmi 14C, announced on August 30, 2024, combines a modern design with robust features, making it a competitive choice in the mid-range smartphone market. Its dimensions of 171.9 x 77.8 x 8.2 mm and a weight of approximately 204 to 211 grams contribute to a solid build quality, featuring a glass front, a plastic frame, and options for a glass back or eco-friendly silicone polymer back.This device supports dual SIM functionality (Nano-SIM, dual stand-by), providing users with the convenience of managing two phone numbers seamlessly.The 6.88-inch IPS LCD display boasts a resolution of 720 x 1640 pixels with a 120Hz refresh rate, enhancing the visual experience with smooth scrolling and vibrant colors. The display also offers a typical brightness of 450 nits, ensuring good visibility even in bright conditions.Powered by the Mediatek Helio G81 Ultra chipset, the Redmi 14C features an octa-core CPU that includes 2x2.0 GHz Cortex-A75 and 6x1.8 GHz Cortex-A55 cores, paired with the Mali-G52 MC2 GPU for efficient graphics performance. The phone comes with various internal storage options ranging from 128GB to 256GB, along with multiple RAM configurations (4GB, 6GB, or 8GB), supporting expandable storage through a microSDXC card slot.The camera system includes a dual main camera setup featuring a 50 MP wide lens and a 2 MP depth lens, complemented by an auxiliary lens. The camera supports features like HDR and can record videos at 1080p. For selfies, the front-facing camera offers a 13 MP sensor, also capable of 1080p video recording.The Redmi 14C is equipped with a 5160 mAh battery, supporting 18W wired charging, which allows for extended usage on a single charge. Connectivity options include Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.4, and a USB Type-C 2.0 port, alongside various positioning systems.",
        thumbnail_1: Redmi14C1,
        thumbnail_2: Redmi14C2,
    },
    {
        id: 6,
        name: "Redmi 13C 8/256",
        original_price: 25000.00,
        current_price: 16500.00,
        discount: "19",
        category: "smartphone",
        image: Redmi13C,
        stock: "In Stock",
        features: {"ram": "8GB", "colors": "Midnight Black, Navy Blue, Glacier White, Clover Green", "battery": "5000 mAh, 18W", "display": "IPS LCD, 6.74 inches, 720 x 1600 pixels, 90Hz", "internal": "256GB", "processor": "Mediatek MT6769Z Helio G85, Octa-core", "main_camera": "50 MP (wide), 2 MP (macro), 0.08 MP (auxiliary)", "front_camera": "8 MP"},
        additional_info: "The Redmi 13C, announced on November 10, 2023, boasts a stylish design with dimensions of 168 x 78 x 8.1 mm and weighs 192 grams. It supports dual SIM functionality, allowing for easy management of two numbers.The device features a vibrant 6.74-inch IPS LCD display with a resolution of 720 x 1600 pixels and a refresh rate of 90Hz, providing smooth scrolling and an immersive viewing experience. The display is protected by Corning Gorilla Glass, ensuring durability against scratches and impacts.Under the hood, the Redmi 13C is powered by the Mediatek MT6769Z Helio G85 chipset, which features an octa-core CPU configuration consisting of 2x2.0 GHz Cortex-A75 and 6x1.8 GHz Cortex-A55 cores, along with the Mali-G52 MC2 GPU for handling graphics.The camera setup includes a dual main camera system with a 50 MP wide lens and a 2 MP macro lens, along with an auxiliary lens for added versatility. It supports features like HDR and can record videos in 1080p at 30fps. For selfies, the front camera is equipped with an 8 MP sensor, also capable of 1080p video recording.The Redmi 13C packs a 5000 mAh battery with 18W wired charging, ensuring long-lasting usage throughout the day. Connectivity options include Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.3, and a USB Type-C 2.0 port, alongside various positioning systems.",
        thumbnail_1: Redmi13C,
    },
    {
        id: 7,
        name: "Redmi Note 13Pro 12/512",
        current_price: 38999.00,
        category: "smartphone",
        image: RedmiNote13Pro2,
        stock: "In Stock",
        features: {"ram": "12GB", "colors": "Midnight Black, Arctic White, Olive Green", "battery": "5100 mAh, 67W", "display": "AMOLED, 6.67 inches, 1220 x 2712 pixels", "internal": "512GB", "processor": "Qualcomm SM7435-AB Snapdragon 7s Gen 2, Octa-core", "main_camera": "200 MP (wide), 8 MP (ultrawide), 2 MP (macro)", "connectivity": "5G", "front_camera": "16 MP"},
        additional_info: "The Redmi Note 13 Pro is a stylish smartphone announced on September 21, 2023, with a sleek design measuring 161.2 x 74.2 x 8 mm and weighing 187 g. It features a glass front (protected by Gorilla Glass Victus), a plastic frame, and a glass back, making it not only durable but also visually appealing.It boasts an AMOLED display that measures 6.67 inches with a resolution of 1220 x 2712 pixels, delivering vibrant colors and deep contrasts, perfect for media consumption. The phone is powered by the Qualcomm SM7435-AB Snapdragon 7s Gen 2 chipset, ensuring smooth performance for everyday tasks and gaming alike.Photography enthusiasts will appreciate the triple main camera setup featuring a 200 MP wide lens, 8 MP ultrawide lens, and a 2 MP macro lens, alongside a 16 MP front camera for stunning selfies. The device also comes equipped with a robust 5100 mAh battery that supports 67W wired charging, ensuring you spend less time plugged in and more time enjoying your device.In terms of connectivity, the Redmi Note 13 Pro supports 5G networks and is equipped with Bluetooth 5.2 and dual-band Wi-Fi for seamless online experiences..",
        thumbnail_1: RedmiNote13Pro2,
        thumbnail_2: RedmiNote13Pro1,
        thumbnail_3: RedmiNote13Pro3,
    },
    {
        id: 8,
        name: "Redmi 13 8/256",
        original_price: 26000.00,
        current_price: 19999.00,
        discount: "9",
        category: "smartphone",
        image: Redmi131,
        stock: "Limited",
        features: {"ram": "8GB", "colors": "Midnight Black, Sandy Gold, Ocean Blue, Pink", "battery": "5030mAh, 33W", "display": "6.79 inches, IPS LCD, 90Hz", "processor": "Mediatek Helio G91 Ultra", "main_camera": "108MP + 2MP", "connectivity": "Dual SIM, 3G, 4G", "front_camera": "13MP", "internal_storage": "256GB"},
        additional_info: "The Redmi 13, announced on June 3, 2024, showcases impressive specifications tailored for budget-conscious users who desire performance and style. It features a sleek body design with dimensions of 168.6 x 76.3 x 8.3 mm and weighs 205 g, providing a comfortable grip. The construction combines a glass front and back with a plastic frame, along with an IP53 rating, ensuring it is dust and splash resistant.The phone sports a 6.79-inch IPS LCD display that supports a 90Hz refresh rate, enhancing the overall visual experience. With a resolution of 1080 x 2460 pixels, the display delivers sharp and vibrant images, perfect for media consumption and gaming. The screen is protected by Corning Gorilla Glass, providing durability against scratches and impacts.At its core, the Redmi 13 is powered by the Mediatek Helio G91 Ultra chipset, featuring an octa-core CPU configuration that includes 2x 2.0 GHz Cortex-A75 and 6x 1.8 GHz Cortex-A55. This processing power ensures smooth multitasking and gaming capabilities. Coupled with 6GB or 8GB of RAM and storage options of 128GB or 256GB, users can enjoy efficient performance and ample space for apps and media.Photography enthusiasts will appreciate the dual-camera setup on the back, which includes a 108MP main camera for high-resolution shots and a 2MP macro lens for detailed close-ups. The 13MP front camera is ideal for selfies and video calls, also capable of capturing HDR images.The device is backed by a robust 5030mAh battery, which supports 33W wired charging, ensuring users can stay connected throughout the day without worrying about battery life. With connectivity options including Dual SIM, 3G, 4G, and Wi-Fi, the Redmi 13 caters to various communication needs.",
        thumbnail_1: Redmi131,
        thumbnail_2: Redmi132,
    },
    {
        id: 9,
        name: "Redmi Note 13 Pro+",
        original_price: 78000.00,
        current_price: 55999.00,
        discount: "21",
        category: "smartphone",
        image: RedmiNote13ProPlus1,
        stock: "Limited",
        features: {"ram": "12GB", "colors": "Midnight Black, Moonlight White, Aurora Purple, Camo Green", "battery": "5000 mAh, 120W ", "display": "AMOLED, 6.67 inches, 1220 x 2712 pixels", "internal": "512GB", "processor": "Mediatek Dimensity 7200 Ultra, Octa-core", "main_camera": "200 MP (wide), 8 MP (ultrawide), 2 MP (macro)", "connectivity": "5G", "front_camera": "16 MP"},
        additional_info: "The Redmi Note 13 Pro+ is a feature-rich smartphone that balances performance and aesthetics. It is powered by the Mediatek Dimensity 7200 Ultra chipset, delivering impressive processing capabilities with its octa-core CPU. This makes it suitable for various tasks, including gaming and multitasking.With memory configurations of 8GB, 12GB, or 16GB of RAM paired with 256GB or 512GB of internal storage, users can select the variant that best meets their needs for app installations and data storage.The device features a stunning 6.67-inch AMOLED display with a resolution of 1220 x 2712 pixels, offering vibrant colors and sharp details. The display supports Dolby Vision and HDR10+, enhancing the viewing experience for media consumption.Photography is a highlight of the Redmi Note 13 Pro+, equipped with a 200 MP main camera, complemented by an 8 MP ultrawide and a 2 MP macro lens, allowing for versatile shooting options. The 16 MP front camera is perfect for selfies and video calls.Powering the device is a 5000 mAh battery, ensuring long-lasting usage. The phone supports 120W wired charging, which can recharge the device to full capacity in just 19 minutes, catering to users with a busy lifestyle.",
        thumbnail_1: RedmiNote13ProPlus1,
        thumbnail_2: RedmiNote13ProPlus2,
        thumbnail_3: RedmiNote13ProPlus3,
    },
    {
        id: 10,
        name: "Redmi Note 13 6/128",
        original_price: 29000.00,
        current_price: 19999.00,
        discount: "18",
        category: "smartphone",
        image: RedmiNote131,
        stock: "Limited",
        features: {"RAM": "6GB, 8GB", "colors": "Midnight Black, Mint Green, Ice Blue, Ocean Sunset", "battery": "5000mAh, 33W", "display": "6.67 inches, AMOLED, 120Hz", "processor": "Qualcomm SM6225 Snapdragon 685", "main_camera": "108MP + 8MP + 2MP", "connectivity": "Dual SIM, 3G, 4G, Wi-Fi", "front_camera": "16MP", "internal_storage": "128GB, 256GB", "operating_system": "Android 13, MIUI 14"},
        additional_info: "The Redmi Note 13 stands out with its high-resolution 108MP main camera, which is rare in this price category. It offers a versatile photography experience with additional 8MP ultra-wide and 2MP macro lenses, making it ideal for users who love capturing detailed photos. The phone excels in different lighting conditions, allowing for great shots, whether close-ups, wide-angle landscapes, or everyday scenes.The phone’s 6.67-inch AMOLED display with a 120Hz refresh rate provides a smooth and fluid user experience, whether for gaming, browsing, or media consumption. The AMOLED panel ensures vivid colors and deep contrasts, enhancing video playback quality and gaming visuals. The 120Hz refresh rate reduces motion blur, making interactions smoother and more responsive.Powered by the Qualcomm Snapdragon 685, this device guarantees fast and efficient performance. Whether running multiple apps or playing graphics-intensive games, the Snapdragon processor ensures a seamless experience without noticeable lag, making it an excellent choice for both productivity and entertainment.In addition to its performance, the Redmi Note 13 boasts a 5000mAh battery that can easily last a full day of heavy usage. With 33W fast charging, users can quickly recharge their phones, minimizing downtime and maximizing convenience. This feature is especially useful for those who are always on the go.",
        thumbnail_1: RedmiNote131,
        thumbnail_2: RedmiNote133,
    },
    {
        id: 11,
        name: "Redmi A3x 4/128",
        original_price: 17500.00,
        current_price: 12200.00,
        discount: "8",
        category: "smartphone",
        image: RedmiA3x3,
        stock: "Limited",
        features:{"RAM": "4GB", "colors": "Midnight Black, Moonlight White, Aurora Green", "battery": "5000mAh, 10W", "display": "6.71 inches, IPS LCD, 720x1650 pixels, 90Hz", "processor": "Unisoc T603 (22nm)", "main_camera": "8MP wide + 0.08MP auxiliary lens", "connectivity": "Dual SIM, 4G", "front_camera": "5MP", "internal_storage": "128GB (with microSD)"},
        additional_info: "The Redmi A3x stands out as an entry-level phone that offers key features catering to budget-conscious users. One of its notable strengths is its 5000mAh battery, which is designed for extended use, ensuring that users can comfortably get through a full day of regular usage without needing to recharge. This is ideal for those who rely heavily on their phone for calls, messages, and casual browsing. Though the charging speed is limited to 10W, it's sufficient for users who prioritize battery life over fast charging.The phone's display is a 6.71-inch IPS LCD panel, offering a 720x1650 resolution. While not as sharp as higher-end models, the screen size and resolution are appropriate for watching videos, browsing, or reading text. The 90Hz refresh rate is a standout feature in this price range, making for smoother scrolling and better responsiveness during everyday tasks.Performance-wise, the Redmi A3x is powered by the Unisoc T603 processor, which handles basic multitasking, light gaming, and social media apps well. With 3GB or 4GB of RAM, this device is built for efficiency, though heavy apps or intense gaming may stretch its limits. The internal storage options of 64GB or 128GB are complemented by microSD support, giving users the flexibility to expand storage if needed.",
        thumbnail_1: RedmiA3x3,
        thumbnail_2: RedmiA3x2,
        thumbnail_3: RedmiA3x1,
    },
    {
        id: 12,
        name: "Redmi 14C 8/256",
        current_price: 16999.00,
        category: "smartphone",
        image: Redmi14C1,
        stock: "In Stock",
        features: {"OS": "Android 14, HyperOS", "Weight": "204 / 207 / 211 g", "Battery": "5160mAh, 18W ", "Display": "6.88-inch IPS LCD, 120Hz, 720 x 1640 pixels", "Network": "GSM / HSPA / LTE", "Processor": "Mediatek Helio G81 Ultra, Octa-core", "Dimensions": "171.9 x 77.8 x 8.2 mm", "Main_Camera": "Dual: 50 MP (wide), 2 MP (depth)", "Selfie_Camera": "13 MP"},
        additional_info: "The Redmi 14C, announced on August 30, 2024, combines a modern design with robust features, making it a competitive choice in the mid-range smartphone market. Its dimensions of 171.9 x 77.8 x 8.2 mm and a weight of approximately 204 to 211 grams contribute to a solid build quality, featuring a glass front, a plastic frame, and options for a glass back or eco-friendly silicone polymer back.This device supports dual SIM functionality (Nano-SIM, dual stand-by), providing users with the convenience of managing two phone numbers seamlessly.The 6.88-inch IPS LCD display boasts a resolution of 720 x 1640 pixels with a 120Hz refresh rate, enhancing the visual experience with smooth scrolling and vibrant colors. The display also offers a typical brightness of 450 nits, ensuring good visibility even in bright conditions.Powered by the Mediatek Helio G81 Ultra chipset, the Redmi 14C features an octa-core CPU that includes 2x2.0 GHz Cortex-A75 and 6x1.8 GHz Cortex-A55 cores, paired with the Mali-G52 MC2 GPU for efficient graphics performance. The phone comes with various internal storage options ranging from 128GB to 256GB, along with multiple RAM configurations (4GB, 6GB, or 8GB), supporting expandable storage through a microSDXC card slot.The camera system includes a dual main camera setup featuring a 50 MP wide lens and a 2 MP depth lens, complemented by an auxiliary lens. The camera supports features like HDR and can record videos at 1080p. For selfies, the front-facing camera offers a 13 MP sensor, also capable of 1080p video recording.The Redmi 14C is equipped with a 5160 mAh battery, supporting 18W wired charging, which allows for extended usage on a single charge. Connectivity options include Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.4, and a USB Type-C 2.0 port, alongside various positioning systems..",
        thumbnail_1: Redmi14C1,
        thumbnail_2: Redmi14C2,
        feature_1: "4GB, 6GB, 8GB RAM",
        feature_2: "128GB, 256GB Internal",
        feature_3: "Battery 5160mAh",
        feature_4: "Battery 18W",
        feature_5: "Main Camera 50MP",
        feature_6: "Front Camera 13MP",
        feature_7: "MediaTek Processor",
        feature_8: "6.88 Inches Display",
        feature_9: "Android 14",
        feature_10: "204 - 211 grams",
    },
    
]